q_cache = {}  # policy's json object cache
p_cache = {}  # policy's text cache
annotation_progress = {}
model_name = 'deepset/bert-base-cased-squad2'
TOP_N = 5
TOTAL_TASK_NUM = 3

original_text = '''Schools and England’s second lockdown: further closures would have adverse effects on children and a wider effect on family life.
LSE British Politics and Policy.
November 5th, 2020.
Sandra McNally and Jo Blanden explain how school closures have negative effects on both children and parents, hindering educational outcomes, mental health, work, and general resilience.
Policymakers have concluded that the benefits of keeping schools open during the second English lockdown are greater than the risks of increased transmission among school communities. The risks of school closures are high: learning loss for students that is hard to make up and therefore has potential long-term consequences; as well as much bigger implications for lower socio-economic groups that will widen inequality and reduce social mobility. In addition, losing the childcare provided by schools has wider negative effects on parents’ work and family life. All these negatives are set against the possibility of reducing the risk of COVID transmission if schools shut. But whether and how much the health risk would reduce is by no means certain. Evidence from Germany indicates that school reopenings there are not associated with an increased risk of infection, but this is in the context of a particular set of disease control measures and is not necessarily applicable in other contexts.
During the first national lockdown, the UK government closed all schools in England. They remained open only for the supervision of vulnerable children and those of critical workers. The closure resulted in a loss of face-to-face instructional time, which is likely to have significant adverse effects on students’ educational outcomes. We know this because of evidence gathered from examples where schools have shut down for other reasons (such as teacher strikes) and because of studies that directly evaluate the impact of instructional time on student outcomes.
While all students lose out when schools close, the impact is much greater for some than from others because of huge disparities in the extent to which schools can compensate through the provision of online teaching or how much parents can compensate through home-schooling or other resources. We now have direct evidence on the effect of the first lockdown from several surveys. The evidence finds that inequalities along the lines of family income or type of schooling are very marked. During lockdown, nearly three quarters (74%) of private school pupils were benefitting from full school days – almost twice the proportion of state school pupils (38%); a quarter of pupils had no formal schooling or tutoring at all. Children from higher income households were also more likely to have had online classes provided by their schools, spent much more time on home learning, and had access to resources such as their own study space at home. Children whose parents were out of work were much less likely to have additional resources such as computers, apps and tutors.
Educators are well aware of the need to make up for the learning losses from the first lockdown, although it is very difficult to do this at the level of intensity, speed, and coverage necessary. Plans for a national tutoring programme are in the process of being rolled out. To enforce school shutdowns again before this has even got started may make a bad situation worse. To the extent that learning loss cannot be made up, this will have long-term effects on students. For example, failing to get a good grade in GCSE English has been shown to have important consequences for students’ trajectories with longer-term implications in the labour market. As the Delve Initiative (2020) puts it ‘the skills loss from missing school is not trivial, and is likely to lead to lower earnings, higher risk of poverty and unemployment with impacts on health and life expectancy’.
Closing schools again is likely to have big adverse effects on children’s learning. But this is not the end of the story: many parents struggled with the additional burden of full-time childcare and supervising home learning when schools closed in March. Evidence from surveys in lockdown indicate that working parents struggled to cope with these new demands, and that women were more likely to lose their jobs or be furloughed. When fathers reduced their work, they did a greater share of childcare than usual, although women still did the lion’s share of the extra work. Moreover, during the spring lockdown, 45% of mothers’ work hours and 26% of fathers’ were simultaneously spent taking care of children. Consequently, there were large declines in mental health among those with young children.
Overall, school closures have obvious adverse effects on children – which are large in magnitude – and also have a wider effect on family life which further hinders mental health, work, and general resilience. The costs of further closure should not be underestimated. Indeed, a recent commentary in Science states that ‘If communities prioritize suppressing viral spread in other social gatherings, then children can go to school.’ This is what the government is trying to achieve, and it should continue this path.'''